#!/usr/bin/env bash

set -e

cd "$(dirname $0)"

usage() {
    cat >&2 <<-EOS
usage: `basename $0` [-f] [-n] [-r] [-l LEVEL] [BACKUPNAME]

LEVEL is "daily" (default), "weekly" or "monthly". "daily" creates a new daily
root filesystem backup and a /media/data backup, "weekly" and "monthly" just
move the oldest daily root fs backup to the newest weekly or the oldest weekly
to the newest monthly, and don't create a data backup.

-f means run it in the foreground, i.e. docker client logs container's output
and waits until the container ends. Default is to start the container and exit.

-n means don't try to build the container image, just run the existing image.

-r means don't run the container, only build the image (unless -n was also
specified, in which case this script won't do anything)

BACKUPNAME defaults to "backup1" and refers to the /mnt/BACKUPNAME directory
to backup to, i.e. essentially the backup drive to backup to.
EOS
    exit 1
}

level=daily
docker_opts=-d
build=1
run=1

while getopts 'fnrl:' OPTNAME; do
case "$OPTNAME" in
  "l")
    level="$OPTARG" ;;
  "f")
    docker_opts= ;;
  "n")
    build= ;;
  "r")
    run= ;;
  "?")
    usage ;;
esac
done

shift $(($OPTIND - 1))

backupname="$1"

if [[ -z "$backupname" ]]; then
    backupname="backup1"
fi

if [[ -n "$build" ]]; then
  docker build --tag oklischat/backup backup/
fi

if [[ -n "$run" ]]; then
  docker run $docker_opts --network nas_pubnet --name "backup-${backupname}-${level}-$(date --utc +%Y%m%d_%H%M%SZ)" -v /:/host -e "BACKUPNAME=$backupname" -e "LEVEL=$level" oklischat/backup
fi
