version: '2'


networks:

  pubnet:
    driver: macvlan
    ipam:
      driver: default
      config:
        # dhcp lease range ${LAN_SUBNET}.50..150 => container range ${LAN_SUBNET}.16/28 (.16....31)
        - subnet: ${LAN_SUBNET}.0/24
          ip_range: ${LAN_SUBNET}.16/28
          gateway: ${LAN_GATEWAY}
    driver_opts:
      parent: enp2s0


volumes:

  desktop_etc_ssh:

  ovpn-config:
    external: true

  prom-tsdb:

services:

  www:
    build:
      context: ./www
      args:
        USER_ID: ${USER_ID}
        USER_NAME: ${USER_NAME}
        USERS_GROUP: ${USERS_GROUP}
    image: oklischat/wwwpublish
    hostname: ${BASENAME}www
    networks:
      pubnet:
        ipv4_address: ${LAN_SUBNET}.17
    volumes:
      - /home:/home:ro
      - /media:/media:ro

  desktop:
    build:
      context: ./desktop
      args:
        USER_ID: ${USER_ID}
        USER_NAME: ${USER_NAME}
        USERS_GROUP: ${USERS_GROUP}
        USER_FULLNAME: ${USER_FULLNAME}
        USER_EMAIL: ${USER_EMAIL}
    image: oklischat/desktop
    hostname: ${BASENAME}d
    privileged: true
    networks:
      pubnet:
        ipv4_address: ${LAN_SUBNET}.16
    volumes:
      - desktop_etc_ssh:/etc/ssh
      - /home:/home
      - /media:/media
      - /var/run/docker.sock:/var/run/docker.sock

  files:
    build:
      context: ./samba
    image: oklischat/samba
    hostname: ${BASENAME}files
    networks:
      pubnet:
        ipv4_address: ${LAN_SUBNET}.18
    environment:
      USERID: ${USER_ID}
      GROUPID: ${USERS_GID}
      TZ: 'CET'
      NMBD: 'true'
    volumes:
      - /home:/home
      - /media:/media
    command:
      - '-u'
      - "${USER_NAME};/tmp/password"
      - '-s'
      - "data;/media/data;yes;no;no;${USER_NAME}"

  vpn:
    image: kylemanna/openvpn
    hostname: ${BASENAME}vpn
    networks:
      pubnet:
        ipv4_address: ${LAN_SUBNET}.19
    cap_add:
      - NET_ADMIN
    volumes:
      - ovpn-config:/etc/openvpn 

  vnc:
    image: oklischat/ubuntu-xfce-vnc:1.5.0
    hostname: ${BASENAME}vnc
    networks:
      pubnet:
        ipv4_address: ${LAN_SUBNET}.20
    volumes:
      - /home:/home
      - /media:/media

  prometheus:
    build:
      context: ./prometheus
    image: oklischat/prometheus
    hostname: prom
    networks:
      pubnet:
        ipv4_address: ${LAN_SUBNET}.21
    volumes:
      - prom-tsdb:/prometheus

  cron:
    build:
      context: ./cron
      args:
        USER_ID: ${USER_ID}
        USER_NAME: ${USER_NAME}
        USERS_GROUP: ${USERS_GROUP}
        USER_FULLNAME: ${USER_FULLNAME}
        USER_EMAIL: ${USER_EMAIL}
    image: oklischat/cron
    hostname: ${BASENAME}-cron
    volumes:
      - /home:/home
      - /media:/media
      - /var/run/docker.sock:/var/run/docker.sock

# TODO:
#  - share ${USER_NAME}'s account (passwd/PAM) among containers that access it (desktop, files, maybe www) somehow
#  - more services: mail, backup, monitoring
