version: '2'


networks:

  pubnet:
    driver: macvlan
    ipam:
      driver: default
      config:
        # dhcp lease range 192.168.142.50..150 => container range 192.168.142.16/28 (.16....31)
        - subnet: 192.168.142.0/24
          ip_range: 192.168.142.16/28
          gateway: 192.168.142.1
    driver_opts:
      parent: enp2s0


volumes:

  desktop_etc_ssh:


services:

  www:
    build:
      context: ./www
      args:
        USER_ID: ${USER_ID}
        USER_NAME: ${USER_NAME}
        USERS_GROUP: ${USERS_GROUP}
    image: oklischat/wwwpublish
    hostname: ${BASENAME}www
    networks:
      pubnet:
        ipv4_address: 192.168.142.17
    volumes:
      - /home:/home:ro
      - /media:/media:ro

  desktop:
    build:
      context: ./desktop
      args:
        USER_ID: ${USER_ID}
        USER_NAME: ${USER_NAME}
        USERS_GROUP: ${USERS_GROUP}
        USER_FULLNAME: ${USER_FULLNAME}
        USER_EMAIL: ${USER_EMAIL}
    image: oklischat/desktop
    hostname: ${BASENAME}d
    networks:
      pubnet:
        ipv4_address: 192.168.142.16
    volumes:
      - desktop_etc_ssh:/etc/ssh
      - /home:/home
      - /media:/media

  files:
    build:
      context: ./samba
    image: oklischat/samba
    hostname: ${BASENAME}files
    networks:
      pubnet:
        ipv4_address: 192.168.142.18
    environment:
      USERID: ${USER_ID}
      GROUPID: ${USERS_GID}
      TZ: 'CET'
      NMBD: 'true'
    volumes:
      - /home:/home
      - /media:/media
    command:
      - '-u'
      - "${USER_NAME};/tmp/password"
      - '-s'
      - "data;/media/data;yes;no;no;${USER_NAME}"


# TODO:
#  - share ${USER_NAME}'s account (passwd/PAM) among containers that access it (desktop, files, maybe www) somehow
#  - more services: mail, backup, monitoring
