---

- hosts: all
  name: install required software and create user
  remote_user: "{{ sudo_user }}"
  become: true

  tasks:
    
    - name: upgrade package manager
      ## needed b/c sometimes on older Debian machines/images, repos URLs are outdated and apt-get install fails (404) without a previous update
      vars:
        done_file: "/tmp/{{username}}_configtasks_aptupgrade_ran"
      shell: "test -x /usr/bin/apt-get && /usr/bin/apt-get -y update; touch {{done_file}}"
      args:
        creates: "{{done_file}}"

    - name: install packages
      package: name={{ item }} state=present
      with_items:
        - git
        - ruby

    - name: add user
      user: name={{username}} comment={{full_name}} group={{primary_group}} groups={{other_groups}}
      ## TODO password setting


      
- hosts: all
  name: "set up user's initial .ssh/"
  remote_user: "{{ sudo_user }}"
  become: true

  tasks:
    
    - name: "create user's .ssh/"
      file: path="~{{username}}/.ssh" state=directory owner="{{username}}" group="{{primary_group}}"

    - name: create authorized_keys
      copy: src="~/.ssh/id_rsa.pub" dest="~{{username}}/.ssh/authorized_keys" owner="{{username}}" group="{{primary_group}}"
      

- hosts: all
  name: set up user home
  remote_user: "{{ username }}"

  tasks:
    
    - name: clone home directory
      #git: repo=files.syseleven.de:/home/oklischat/gitrepos/home.git dest=~/hm ssh_opts='-o StrictHostKeyChecking=no'
      shell: "sleep 10 && (id; hostname) >>~/anstest.txt"

      