---

- name: set up known_hosts
  ## TODO if file exists, append, don't overwrite
  copy: src='known_hosts' dest="~/.ssh/known_hosts"

- name: clone home directory into {{tmphome}}
  git:
    repo: "{{home_repo}}"
    dest: "{{tmphome}}"
    recursive: no

- name: move cloned home into final place from {{tmphome}}
  shell: "shopt -s dotglob && mv -f {{tmphome}}/* ~/"
  args:
    executable: "/bin/bash"
    creates: "~/.git"

- name: clone more repositories into ~/
  git:
    repo: "{{item.url}}"
    dest: "{{item.dest}}"
    recursive: no
  with_items: "{{more_repos}}"
  ignore_errors: yes

- name: copy utils/Makefile.conf
  command: cp ~/utils/Makefile.conf.sample ~/utils/Makefile.conf
  args:
    creates: ~/utils/Makefile.conf

- lineinfile: dest=~/utils/Makefile.conf regexp=^SUCOMMAND= line=SUCOMMAND=

- name: make utils
  command: make
  args:
    chdir: ~/utils
