#!/bin/bash

set -e

backupname="$1"
host="$2"
revision="$3"
time="$4"
size="$5"

cat <<EOF | curl -XPOST --data-binary @- "http://pushgateway:9091/metrics/job/backups/backupname/$backupname/host/$host/revision/$revision"
# TYPE backup_size_bytes gauge
# HELP size of a created backup
backup_size_bytes $size
EOF

# for the time of the last backup, use the push gateway's "push_time_seconds" metric, e.g.
# push_time_seconds{job="backups",backupname="backup1",host="tack",revision="daily.0"}
