#!/bin/bash

if [[ -z "$BACKUPNAME" ]]; then
  echo "\$BACKUPNAME unset, aborting" >&2
  exit 1
fi

# exec >>/var/log/backup.tack-$BACKUPNAME.log

sed -i "s/^snapshot_root.*/snapshot_root\t\/host\/mnt\/${BACKUPNAME}\/tack\//" /rsnapshot.conf

/usr/bin/nice /usr/bin/nocache /usr/bin/rsnapshot -c /rsnapshot.conf sync && /usr/bin/nice /usr/bin/nocache /usr/bin/rsnapshot -c /rsnapshot.conf daily
# TODO run "rsnapshot -c /rsnapshot.conf weekly" once per week and "rsnapshot -c /rsnapshot.conf monthly" once per month,
# either from here or via cronjob

# TODO lock file
date '+[%d/%b/%Y:%H:%M:%S] starting data backup'
/usr/bin/nice /usr/bin/nocache /usr/bin/rsync -a --numeric-ids "/host/media/data/" "/host/mnt/$BACKUPNAME/tack/data/"
date '+[%d/%b/%Y:%H:%M:%S] data backup finished'
