---

- hosts: all
  remote_user: "{{ sudo_user }}"
  become: true

  roles:
    - { role: create_user, when: "create_user" }

  vars:
    primary_group: users
    other_groups:
      - sudo
      - src
      - docker
      - systemd-journal

- hosts: all
  remote_user: "{{ username }}"
  roles:
    - setup_user
