---

- name: Setup host and create user
  hosts: all
  remote_user: "{{ sudo_user }}"
  become: true

  vars:
    primary_group: users

  roles:
    - debian_base
    - dockerd
    - create_user
    - admin_packages
    - nas

- name: Setup user
  hosts: all
  remote_user: "{{ username }}"
  roles:
    - setup_user
