#!/usr/bin/env bash

dir="$1"

if [[ -n "$STDOUT" ]]; then
    exec > "$STDOUT"
fi

if [[ -n "$STDERR" ]]; then
    exec 2> "$STDERR"
fi

find "$dir" -mindepth 1 -maxdepth 1 -type f -regex '.*/[a-zA-Z0-9_-]+' -perm -u=x ! -name '*~' | sort -n | while read script; do
    "$script"
    ec="$?"

    cat <<EOF | curl -s -XPOST --data-binary @- "http://pushgateway:9091/metrics/job/cron/dir@base64/$(base64 <<<$dir)/script@base64/$(basename $script | base64)"
# TYPE cron_script_exit_code gauge
# HELP exit code of cron script run
cron_script_exit_code $ec
EOF

done
