---

- name: install packages
  package: name={{ item }} state=present
  with_items:
    - git
    - ruby
    - make
    - net-tools
    - netcat
    - bridge-utils
    - traceroute
    - tcpdump
    #- virtualbox-dkms
